#+TITLE: Flake it till you make it!

The dots used to be managed by a custom [[./bin/bin/make_symlink][script]] that I wrote,
which was very much prone to breakages, so I took a flaky approach.

This is an experimental branch where I'm testing nix.

I wish to work with a single file mindset and see how far I can
take it, that's why I opted to not use home-manager and use
GNU Stow instead for dotfiles symlink.

* References
- [[https://blog.kubukoz.com/flakes-first-steps/][Flakes first steps]]
- [[https://ertt.ca/nix/shell-scripts/][Shell scripts with nix]]
- [[https://blog.mplanchard.com/posts/installing-a-specific-version-of-a-package-with-nix.html][Installing a specific version with nix]] (explains how to work with overlays)
- [[https://www.bekk.christmas/post/2021/16/dotfiles-with-nix-and-home-manager][Declarative management of dotfiles with Nix and Home Manager]]
- [[https://seroperson.me/2024/01/16/managing-dotfiles-with-nix/][Managing dotfiles with nix]]
- [[https://samuel.dionne-riel.com/blog/2024/05/07/its-not-flakes-vs-channels.html][Flakes vs Channels]]

* Installation
- Get the list of packages to replace using =brew leaves=.
- Install nix: =curl -L https://nixos.org/nix/install | sh=.

* Set-up the packages
- Create [[./flake.nix]]
- (Check [[*Macos exclusive stuff]] if you're running darwin)

  Run =nix --extra-experimental-features "nix-command flakes" profile install . --impure= in the dotfiles directory.
- Run =stow <dir>= to symlink the dotfiles. e.g.: =stow nix= (To not link and see what the stow command will do, run =stow -nv linux=)
- To upgrade the packages, run =nix flake update= and then =nix profile upgrade dotfiles --impure=
- To upgrade specific flake inputs =nix flake update emacs-overlay=, to check status of channels [[https://status.nixos.org/][visit this]].
- Remember to run =nix-collect-garbage -d= to clean up old generations and to save space.

* Macos exclusive stuff
- Most of the apps are installed using =nix-homebrew= and system configuration happens via =nix-darwin=
- I have created two aliases for working with darwin, they are =nix-update-mac= and =darwin-rebuild-mac= respectively. These have to set the =HOSTNAME= envVar which is used in the flake file for =darwinConfigurations=.
#+begin_src bash
alias nix-update-mac='HOSTNAME=$(hostname -s) nix build .#darwinConfigurations.$(hostname -s).system --impure'
alias darwin-rebuild-mac='HOSTNAME=$(hostname -s) ./result/sw/bin/darwin-rebuild switch --flake . --impure'
#+end_src
- Refer [[https://nix.dev/guides/troubleshooting#macos-update-breaks-nix-installation][macOS update breaks nix installation]] 

* TODO Check for [[https://discourse.nixos.org/t/declare-firefox-extensions-and-settings/36265/5][declarative browser]] configuration

* TODO Check [[https://yashgarg.dev/posts/nix-devenv/][this]] for WSL setup?
