#+TITLE: My Janky Dotfiles

They're managed by a custom [[./bin/make_symlink][script]] that I wrote, which is
very much prone to breakages, so use it at your own risk.

This is an experimental branch where I'm testing nix.

* References:
- https://blog.kubukoz.com/flakes-first-steps/
- [[https://www.bekk.christmas/post/2021/16/dotfiles-with-nix-and-home-manager][Declarative management of dotfiles with Nix and Home Manager]]
- https://seroperson.me/2024/01/16/managing-dotfiles-with-nix/

* Installation
- Get the list of packages to replace using =brew leaves=.
- Install nix: =curl -L https://nixos.org/nix/install | sh=.
- Try running: =nix-shell -p nix-info --run "nix-info -m"=
  This builds a temporary environment where it installs =nix-info= package and runs
  =nix-info -m= in the temporary shell.

* Set-up the packages
- Create [[./flake.nix]]
- Run =nix --extra-experimental-features "nix-command flakes" profile install .= in the dotfiles directory.
- Run =stow <dir>= to symlink the dotfiles. e.g.: =stow nix=
- To upgrade the packages, run =nix flake update= and then =nix profile upgrade dotfiles=
- To install emacs from emacs-overlay, use =nix profile install emacs-overlay#emacs-unstable=
