# infat --config ~/.config/infat/config.toml
[types]
text = "Emacs"
plain-text = "Emacs"
makefile = "Emacs"
sourcecode = "Emacs"
unix-executable = "Kitty"
video = "Mpv"
movie = "Mpv"
mp4-audio = "Mpv"
mp4-movie = "Mpv"

# infat set --type m3u Mpv
[extensions]
md = "Emacs"
m3u = "Mpv"
