[[manager.prepend_keymap]]
on  = [ "+" ]
run = 'create'

[[manager.prepend_keymap]]
on  = [ "m" ]
run = [ 'select --state=true', 'arrow 1' ]

[[manager.prepend_keymap]]
on = [ "u" ]
run = [ 'select --state=false', 'arrow 1' ]
