[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "red", bg = "black" }

# Mode
mode_normal = { fg = "black", bg = "lightblue",    bold = false }
mode_select = { fg = "black", bg = "lightgreen",   bold = false }
mode_unset  = { fg = "black", bg = "lightmagenta", bold = false }
