#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config ignore_ewmh_focus true

bspc monitor -d I II III IV
# VIII IX X

bspc config border_width         3
bspc config window_gap           10
# 8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# Mouse support is garbage
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Pavucontrol state=floating rectangle=600x300+1020+30
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=tiled
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a MEGAsync state=floating rectangle=400x500+1450+450
# bspc rule -a 'Emacs:emacs-anywhere' state=floating sticky=on rectangle=1500x700+210+190
# bspc rule -a 'emacs-everywhere' state=floating sticky=on rectangle=1500x700+210+190
bspc rule -a chatterino state=tiled split_ratio 0.80
bspc rule -a 'emacs-anywhere' state=floating sticky=on rectangle=1500x700+210+190
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled desktop='^1' follow=on
bspc rule -a Code state=tiled desktop='^2' follow=on
bspc rule -a Microsoft-edge desktop='^3' follow=on
bspc rule -a Teams state=tiled desktop='^4' follow=on
bspc rule -a Zathura state=tiled
# Scratch: wxh+x+y
bspc rule -a '*:scratch' state=floating sticky=on rectangle=1500x700+210+190
bspc rule -a 'ru-turikhay-tlauncher-bootstrap-Bootstrap' state=pseudo_tiled

# HELP: xprop | grep WM_CLASS

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#817c9c"
bspc config active_border_color         "#1b2124"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Conky
conky -c ~/.config/conky/conky.conf &
# conky -c ~/.config/conky/compre.conf &
# Bar
# killall -q polybar; polybar -r left & polybar -r center & polybar -r right &
killall -q polybar; polybar -r top &
# ~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
~/bin/wall.sh &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &
# mpd
pkill mpd; mpd &

# Cursor
xsetroot -cursor_name left_ptr &

# Annoying bell off
xset b off &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

# Emacs server
emacs --daemon &

# YAMS Scrobbler daemon
yams -k; yams &

# watcher -ds / -ws
# killall watcher; watcher --start &
