#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config ignore_ewmh_focus true

bspc monitor -d I II III IV V
# VIII IX X

bspc config border_width         2
bspc config window_gap           5 # 8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

# Mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Pavucontrol state=floating rectangle=600x300+1120+730
bspc rule -a Blueman-manager state=floating rectangle=500x400+1350+630
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=tiled
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a MEGAsync state=floating rectangle=400x500+1450+450
bspc rule -a 'Gnome-pomodoro' state=floating rectangle=300x400+20+20
bspc rule -a 'Emacs:doom-capture' state=floating sticky=on rectangle=1500x700+210+190
# bspc rule -a 'Emacs:emacs-anywhere' state=floating sticky=on rectangle=1500x700+210+190
# bspc rule -a 'emacs-everywhere' state=floating sticky=on rectangle=1500x700+210+190
bspc rule -a chatterino state=floating split_ratio 0.80
bspc rule -a 'emacs-anywhere' state=floating sticky=on rectangle=1500x700+210+190
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled # desktop='^1' follow=on
bspc rule -a Code state=tiled desktop='^2' follow=on
bspc rule -a Microsoft-edge # desktop='^3' follow=on
bspc rule -a 'Microsoft Teams - Preview' state=tiled desktop='^4' 
bspc rule -a Zathura state=tiled
bspc rule -a 'easyeffects' state=floating
# Scratch: wxh+x+y
bspc rule -a '*:scratch' state=floating sticky=on rectangle=1500x700+210+190
bspc rule -a 'nmtui' state=floating rectangle=500x550+20+450
bspc rule -a 'ru-turikhay-tlauncher-bootstrap-Bootstrap' state=pseudo_tiled

# HELP: xprop | grep WM_CLASS

# Border
bspc config focused_border_color        "#BD93F9"  # "#009688"
bspc config normal_border_color         "#817c9c"
bspc config active_border_color         "#1b2124"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
conky -c ~/.config/conky/conky.conf &
conky -c ~/Dotfiles/.config/conky/tracker.conf &
pkill mpd; mpd &
/usr/bin/dunst &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
picom -CGb --window-shader-fg=/home/prashant/config/bw_picom.glsl &
nm-applet --indicator &
xsetroot -cursor_name left_ptr &
xset b off &
~/.config/bspwm/scripts/low_bat_notifier.sh
yams -k; yams &
setxkbmap -option caps:ctrl_modifier,shift:both_capslock &
fcitx5 --replace -d &
xterm -e "~/bin/startup" & # why does this need a terminal? ;-;
# killall -q polybar; polybar -r left & polybar -r center & polybar -r right &
# pgrep ~/.config/bswpm/bspswallow || ~/.config/bspwm/bspswallow &
pgrep rclone || rclone mount dropbox: ~/Dropbox/ --allow-non-empty --daemon &
