k9s:
  cluster: kind-kind
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
    - cert-manager-test
    - cert-manager
  view:
    active: ns
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
