# Needs to be run as "dictd -c ~/.dictd.conf --pid-file /tmp/dictd.pid"
# To debug: "dictd -c ~/.dictd.conf --debug nodetach"
access {
    allow localhost
    deny *
}

database jpn2eng {
    data /Users/I752152/.nix-profile/share/dictd/jpn-eng.dict.dz
    index /Users/I752152/.nix-profile/share/dictd/jpn-eng.index
}