# Needs to be run as "dictd -c ~/.dictd.conf --pid-file /tmp/dictd.pid"
# To debug: "dictd -c ~/.dictd.conf --debug nodetach"
access {
    allow localhost
    deny *
}

database jpn2eng {
    data /Users/I752152/dotfiles/dict/jpn-eng.dict.dz
    index /Users/I752152/dotfiles/dict/jpn-eng.index
}

database gcide {
    data /Users/I752152/dotfiles/dict/gcide.dict.dz
    index /Users/I752152/dotfiles/dict/gcide.index
}
