# The basic colors
foreground              #eae8e1
background              #202225
selection_foreground    #202225
selection_background    #eae8e1

# Cursor colors
cursor                  #00C2FF
cursor_text_color       #222323

# URL underline color when hovering with mouse
url_color               #CCCCCC

# Tab bar colors
active_tab_foreground   #eae8e1
active_tab_background   #202225
inactive_tab_foreground #3F4451
inactive_tab_background #202225

# The 16 terminal colors

# black
color0 #3F4451
color8 #4F5666

# red
color1 #E06C75
color9 #BE5046

# green
color2  #98C379
color10 #A5E075

# yellow
color3  #D19A66
color11 #E5C07B

# blue
color4  #61AFEF
color12 #4DC4FF

# purple
color5  #C678DD
color13 #DE73FF

# cyan
color6  #56B6C2
color14 #4CD1E0

# white
color7  #eae8e1
color15 #eae8e1
