include theme.conf
# shell fish -l -i # $HOME/.nix-profile/bin/fish -l -i

background_opacity 0.95
background_blur 30
cursor_blink_interval 1.6 #ease-in-out
# cursor_trail 200
# cursor_trail_decay 0.1 0.2
# cursor_trail_start_threshold 5

# Perf? src: sxyazi
input_delay 0
sync_to_monitor no

# MacOS
font_family      VictorMono Nerd Font Mono SemiBold
italic_font      VictorMono Nerd Font Mono SemiBold Italic
font_size        14
# font_family      VictorMono NFM SemiBold
# italic_font      VictorMono NFM SemiBold Italic
# font_size        13.5
bold_font        VictorMono Nerd Font Mono Bold
bold_italic_font VictorMono Nerd Font Mono Bold Italic
font_features    VictorMono-SemiBold +ss01
modify_font underline_position 9
modify_font underline_thickness 120%
adjust_line_height 115%
include font-nerd-symbols.conf

kitty_mod command+shift
map kitty_mod+plus  change_font_size all +1.0
map kitty_mod+minus change_font_size all -1.0
map kitty_mod+c     copy_to_clipboard
map kitty_mod+v     paste_from_clipboard
map shift+insert    paste_from_clipboard
map kitty_mod+6     set_colors --all --configured ~/.config/kitty/theme-light.conf
map kitty_mod+7     set_colors --all --configured ~/.config/kitty/theme.conf
# use left click only to go to a link instead of S-click
mouse_map left click ungrabbed no_op
mouse_map left click ungrabbed,grabbed mouse_handle_click selection link prompt
mouse_map right press grabbed,ungrabbed paste_from_selection
copy_on_select yes

strip_trailing_spaces smart
select_by_word_characters ${}/&@_.
allow_remote_control yes
# for theme change
listen_on unix:/tmp/mykitty

window_padding_width 5 5 5

# macos
hide_window_decorations titlebar-only
macos_option_as_alt yes
macos_show_window_title_in none

tab_bar_style separator
tab_separator ""
active_tab_font_style   normal
tab_title_template " {title} "
active_tab_title_template " {title} "

# startup_session launch.conf
